### ISSUE TITLE
migrate Google Analytics from UA to GA4

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/commonui-bs3-2019#11]
We should move from current GA (UA) to GA4 soon, so we have a reasonable history by the time UA stops working mid 2023.

https://support.google.com/analytics/answer/10759417?hl=en&ref_topic=12154439,12153943,2986333,&visit_id=637939655785274378-3265664372&rd=1

**Comment by temi** [comment]
Profiles has dependency on GA to get page statistics. It will require some investigation to see if existing features can be supported or need to be removed.

**Comment by matthewandrews** [comment]
Hi @temi - sure.  The plan is to add GA4 to commonui (and home) soon, but not remove the existing UA.  So data will go to both until UA stops mid 2023.

**Comment by matthewandrews** [comment]
Our GA4 web tag has now been added to commonui-bs3-2019 and the home site (in test and prod).

**Comment by sat01a** [comment]
Web app GA4 - BioCollect, DigiVol, MERIT, Profiles 
Mobile app GA4 - iOS and Android apps

**Comment by TaniaGLaity** [comment]
first draft circulated to Systems team for discussion / review
[UAvsGA4.docx](https://github.com/AtlasOfLivingAustralia/commonui-bs3-2019/files/9449565/UAvsGA4.docx)

**Comment by matthewandrews** [comment]
Given that EU countries are outlawing GA including GA4 we are now moving to a different analytics system.
